- source: data-ms.qmd
  quarto-pub:
    - id: 9a6058fa-93f7-4e40-b285-69e581d80499
      url: 'https://nballou.quarto.pub/a-multi-platform-dataset-of-digital-trace-data-from-video-games'
jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
